# Site settings
author: Katie Blizzard
title: KB x Coding 
header-img: img/home-bg.png
email: kblizzard11@gmail.com
copyright_name: Katie Blizzard
description: > # this means to ignore newlines until "baseurl:"
  Explorations in Coding ft. Personal and Professional Interests
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ktbliz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
